### PR TITLE
List and decompile all functions to extract pcode

### PR DESCRIPTION
**Pull request by kumarak**
https://github.com/lifting-bits/patchestry/issues/43

### CODE REVIEW

**Comment by kumarak** [comment]
CI passes the test but running lit test locally giving me same error on both Ubuntu and macos. It is related to directory permission in the docker. Still investigating it.

```
********************
FAIL: PatchestryTest :: ghidra/struct.c (19 of 19)
******************** TEST 'PatchestryTest :: ghidra/struct.c' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
Error: Failed to change permissions on output file '/mnt/output/struct.c.tmp'.

--
Command Output (stderr):
--```

**Comment by kumarak** [comment]
It was due to the mounting of directory in docker container. I added a sanity check in script for path that verifies input/output exist and ci path directory is absolute to avoid any issues related to wrong directory getting mounted.

**Comment by xlauko** [comment]
Can you add a 2 tests please. One to list all functions and one to decompile all functions.

**Comment by kumarak** [comment]
@xlauko, I added a few test cases to test `--list-functions` flag and decompile all feature.

**Comment by xlauko** [comment]
You don't need to make copies of files, one file can have multiple RUNS with specific checks:

```
// RUN: %decompile-headless --input %t.o --output %t %ci_output_folder
// RUN: %file-check %s -check-prefix=DECOMPILE

// RUN: %decompile-headless --input %t.o --list-functions --output %t %ci_output_folder
// RUN: %file-check %s -check-prefix=LISTFNS

// DECOMPILE: <check expected output for decompilation>

// LISTFNS: <check expected output for listed functions>
```

**Comment by kumarak** [comment]
@xlauko, Thanks for the pointer. I looked into the `--check-prefix` but didn't thought above using them in the same test case. It is nice to remove redundancies. 

I updated the unit case to use --check-prefix in FileCheck.

**Review by xlauko — APPROVED** [review]

**Pull request merged**
